In [1]:
import numpy as np

In [4]:
A = np.asarray([[2,1,2],
              [1,-2,1],
              [1,2,3],
              [1,1,1]])


In [5]:
b= np.asarray([[6],[1],[5],[2]])

In [ ]:
# x=(A⊤A)−1 A⊤b

In [8]:
ATA_inverse = np.linalg.inv(A.transpose() @ A)

In [9]:
ATA_inverse


array([[ 0.72142857,  0.12857143, -0.49285714],
       [ 0.12857143,  0.17142857, -0.15714286],
       [-0.49285714, -0.15714286,  0.43571429]])

In [10]:
ATb = A.transpose() @ b

In [14]:
x = ATA_inverse @ ATb


In [15]:
x

array([[1.7],
       [0.6],
       [0.7]])

In [16]:
r = (A@x) - b 

In [17]:
r


array([[-6.00000000e-01],
       [ 2.00000000e-01],
       [-3.55271368e-15],
       [ 1.00000000e+00]])

In [18]:
## part c

In [21]:
W = np.eye(4)

In [34]:
W[0,0] = 1000 

In [35]:
W
# we set value at W[0,0] to 1000 in order to move the decimal of -0.6.... three spaces right

array([[1000.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.],
       [   0.,    0.,    1.,    0.],
       [   0.,    0.,    0.,    1.]])

In [36]:
ATWA = A.transpose() @ W @ A

In [37]:
ATWA

array([[4003., 2001., 4005.],
       [2001., 1009., 2005.],
       [4005., 2005., 4011.]])

In [38]:
ATWb = A.transpose() @ W @ b

In [39]:
ATWb


array([[12008.],
       [ 6010.],
       [12018.]])

In [40]:
ATWA_inverse = np.linalg.inv(ATWA)

In [41]:
ATWA_inverse

array([[ 0.26023684,  0.0385828 , -0.27913415],
       [ 0.0385828 ,  0.15386981, -0.11544081],
       [-0.27913415, -0.11544081,  0.33667192]])

In [42]:
x = ATWA_inverse @ ATWb

In [43]:
x

array([[2.17244031],
       [0.69218347],
       [0.48106425]])

In [44]:
r = A@x - b

In [45]:
r # R1 is less than 0.001

array([[-8.07412821e-04],
       [ 2.69137606e-01],
       [-1.36424205e-12],
       [ 1.34568803e+00]])