In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [73]:
df = pd.read_csv('data.csv')

In [74]:
df = df[(df['iso_code']=='FRA') | (df['iso_code']=='GBR') | (df['iso_code']=='ITA')|
        (df['iso_code']=='CHE') | (df['iso_code']=='DEU') | (df['iso_code']=='PRT') ]

In [75]:
df = df[(df['date'] >= '2020-03-15') & (df['date'] <= '2020-11-09')]

In [76]:
df.head()

iso_code continent location        date  total_cases  new_cases  \
17891      FRA    Europe   France  2020-03-15       4499.0      838.0   
17892      FRA    Europe   France  2020-03-16       5423.0      924.0   
17893      FRA    Europe   France  2020-03-17       6633.0     1210.0   
17894      FRA    Europe   France  2020-03-18       7730.0     1097.0   
17895      FRA    Europe   France  2020-03-19       9134.0     1404.0   

       new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
17891             540.429          91.0        12.0               11.571  ...   
17892             613.857         127.0        36.0               15.429  ...   
17893             745.857         148.0        21.0               16.857  ...   
17894             849.429         175.0        27.0               20.286  ...   
17895             979.000         244.0        69.0               28.000  ...   

       gdp_per_capita  extreme_poverty  cardiovasc_death_rate  \
17891       38605.671              NaN                  86.06   
17892       38605.671              NaN                  86.06   
17893       38605.671              NaN                  86.06   
17894       38605.671              NaN                  86.06   
17895       38605.671              NaN                  86.06   

       diabetes_prevalence  female_smokers  male_smokers  \
17891                 4.77            30.1          35.6   
17892                 4.77            30.1          35.6   
17893                 4.77            30.1          35.6   
17894                 4.77            30.1          35.6   
17895                 4.77            30.1          35.6   

       handwashing_facilities  hospital_beds_per_thousand  life_expectancy  \
17891                     NaN                        5.98            82.66   
17892                     NaN                        5.98            82.66   
17893                     NaN                        5.98            82.66   
17894                     NaN                        5.98            82.66   
17895                     NaN                        5.98            82.66   

       human_development_index  
17891                    0.901  
17892                    0.901  
17893                    0.901  
17894                    0.901  
17895                    0.901  

[5 rows x 49 columns]

In [77]:
dfSub = df[['location', 'date','new_cases','population', 'population_density']]

In [78]:
#dfSub.to_csv(r'relevantData.csv', index = False)

In [79]:
A = dfSub[dfSub['location']!='France']

In [80]:
A = A[['location','new_cases']]

In [81]:
A.groupby('location').count()

new_cases
location                 
Germany               240
Italy                 240
Portugal              240
Switzerland           240
United Kingdom        240

In [82]:
germ = A[A['location']=='Germany'].reset_index().drop('index',axis=1)
ita = A[A['location']=='Italy'].reset_index().drop('index',axis=1)
port = A[A['location']=='Portugal'].reset_index().drop('index',axis=1)
swi = A[A['location']=='Switzerland'].reset_index().drop('index',axis=1)
unk = A[A['location']=='United Kingdom'].reset_index().drop('index',axis=1)

In [106]:
N = pd.DataFrame(columns=['Germany','Italy','Portugal','United Kingdom'],index = range(0,240))
N['Germany'] = germ['new_cases']
N['Italy']= ita['new_cases']
N['Portugal'] = port['new_cases']
#N['Switzerland'] = swi['new_cases']
N['United Kingdom'] = unk['new_cases']
N

Germany    Italy  Portugal  United Kingdom
0      733.0   3497.0      57.0           478.0
1     1043.0   2823.0      76.0           361.0
2     1174.0   4000.0      86.0           442.0
3     1144.0   3526.0     117.0           611.0
4     1042.0   4207.0     194.0           769.0
..       ...      ...       ...             ...
235  19990.0  30548.0    7497.0         25177.0
236  21506.0  34502.0    4410.0         24138.0
237  23399.0  37802.0    5550.0         23287.0
238  16017.0  39809.0    6640.0         24957.0
239  13363.0  32614.0    5784.0         20572.0

[240 rows x 4 columns]

In [107]:
A = N.to_numpy()
A

array([[  733.,  3497.,    57.,   478.],
       [ 1043.,  2823.,    76.,   361.],
       [ 1174.,  4000.,    86.,   442.],
       [ 1144.,  3526.,   117.,   611.],
       [ 1042.,  4207.,   194.,   769.],
       [ 5940.,  5322.,   143.,   999.],
       [ 4049.,  5986.,   235.,  1055.],
       [ 3276.,  6557.,   260.,  1255.],
       [ 3311.,  5560.,   320.,  1198.],
       [ 4438.,  4789.,   460.,  1378.],
       [ 2342.,  5249.,   302.,  2338.],
       [ 4954.,  5210.,   633.,  2375.],
       [ 5780.,  6153.,   549.,  2692.],
       [ 6294.,  5959.,   724.,  3087.],
       [ 3965.,  5974.,   902.,  3197.],
       [ 4751.,  5217.,   792.,  2822.],
       [ 4615.,  4050.,   446.,  2858.],
       [ 5453.,  4053.,  1035.,  4273.],
       [ 6156.,  4782.,   808.,  4514.],
       [ 6174.,  4668.,   783.,  4913.],
       [ 6082.,  4585.,   852.,  4868.],
       [ 5936.,  4805.,   638.,  4911.],
       [ 3677.,  4316.,   754.,  4020.],
       [ 3834.,  3599.,   452.,  3592.],
       [ 4003., 

In [108]:
b = dfSub[dfSub['location']=='France']

In [109]:
b = b[['new_cases']]

In [110]:
b=b.to_numpy()
b

array([[ 8.3800e+02],
       [ 9.2400e+02],
       [ 1.2100e+03],
       [ 1.0970e+03],
       [ 1.4040e+03],
       [ 1.8610e+03],
       [ 1.6170e+03],
       [ 1.8470e+03],
       [ 1.5590e+03],
       [ 3.8380e+03],
       [ 2.4460e+03],
       [ 2.9310e+03],
       [ 3.9220e+03],
       [ 3.8090e+03],
       [ 4.6110e+03],
       [ 2.5990e+03],
       [ 4.3760e+03],
       [ 7.5780e+03],
       [ 4.8610e+03],
       [ 2.1160e+03],
       [ 5.2330e+03],
       [ 4.2670e+03],
       [ 1.8730e+03],
       [ 3.9120e+03],
       [ 3.7770e+03],
       [ 3.8810e+03],
       [ 4.2860e+03],
       [ 4.3420e+03],
       [ 3.1140e+03],
       [ 1.6130e+03],
       [ 2.6730e+03],
       [ 5.4970e+03],
       [ 2.6330e+03],
       [ 2.6410e+03],
       [ 4.0500e+02],
       [ 2.5690e+03],
       [ 7.8500e+02],
       [ 2.0510e+03],
       [ 2.6670e+03],
       [ 1.8270e+03],
       [ 1.6530e+03],
       [ 1.7730e+03],
       [ 1.5370e+03],
       [ 4.6100e+02],
       [ 1.1950e+03],
       [ 1

In [111]:
A_train = A[:230]
b_train = b[:230]
A_test = A[230:]
b_test = b[230:]

In [112]:
 x = (np.linalg.inv((A_train.transpose()@A_train)))@A_train.transpose()@b_train

In [113]:
x

array([[-1.31830176],
       [ 1.04584864],
       [ 6.94119629],
       [ 0.50876567]])

In [114]:
predictions = A_test@x

In [115]:
predictions

array([[52113.05281445],
       [53485.37863243],
       [48413.387205  ],
       [30070.44856807],
       [35046.38175751],
       [70443.07400322],
       [50623.7335801 ],
       [59059.49304386],
       [79305.75750879],
       [67107.04790991]])

In [116]:
b_test

array([[49215.],
       [32641.],
       [49290.],
       [52518.],
       [36330.],
       [40558.],
       [58046.],
       [60486.],
       [86852.],
       [38619.]])

In [103]:
N['Switzerland'][N['Switzerland']==0]

2      0.0
74     0.0
98     0.0
99     0.0
189    0.0
190    0.0
197    0.0
203    0.0
204    0.0
207    0.0
210    0.0
211    0.0
217    0.0
224    0.0
225    0.0
231    0.0
232    0.0
238    0.0
239    0.0
Name: Switzerland, dtype: float64